name: create-release
on:
  workflow_dispatch:
env:
  ACTIONS_RUNNER_DEBUG: false
jobs:
  login-to-docker:
    name: Test Docker
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  test-and-linting:
      uses: ./.github/workflows/pull_request.yml
  docker:
    runs-on: ubuntu-latest
    needs: test-and-linting

    if: ${{ success() }}
    env:
      REGISTRY_ID: crpkbormehnpcu7gaie8
      YC_CREDS: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
    steps:
      - uses: actions/checkout@v4

      - name: Create new release branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: v${{ github.run_number }}
          sha: ${{ github.event.pull_request.head.sha }}

      - name: Create docker image
        run: docker build . -t cr.yandex/${{ env.REGISTRY_ID }}/app:${{ github.run_number }} -t cr.yandex/${{ env.REGISTRY_ID }}/app:${{ github.run_number }}_latest

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ env.YC_CREDS }}
      - name: Push docker image to Container registry
        run: docker push -a cr.yandex/${{ env.REGISTRY_ID }}/app
  update-repo:
    runs-on: ubuntu-latest
    needs: docker
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create git tag
        run: |
          git tag v${{ github.run_number }}
          git push origin v${{ github.run_number }}

      - name: Get current version
        id: get_current_version
        run: echo "current_version=v${{ github.run_number }}" >> $GITHUB_ENV

      - name: Get previous version
        id: get_previous_version
        run: echo "previous_version=v$(( ${{ github.run_number }} - 1 ))" >> $GITHUB_ENV

      - name: Get commits between versions
        id: get_commits
        run: |
          commits=$(git log --pretty=oneline ${{ env.previous_version }}...${{ env.current_version }})
          echo "commits=$commits" >> $GITHUB_ENV

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y/%m/%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Create issue
        uses: dacbd/create-issue-action@main
        env:
          REGISTRY_ID: crpkbormehnpcu7gaie8
        with:
          token: ${{ github.token }}
          title: ${{ github.triggering_actor }} made release v${{ github.run_number }}
          labels: CICD
          body: |
            date: ${{ env.NOW }}
            author: @${{ github.triggering_actor }}
            version: ${{ github.run_number }}
            docker-image: cr.yandex/${{ env.REGISTRY_ID }}/app:${{ github.run_number }}
            commits between ${{ env.previous_version }} and ${{ env.current_version }}: ${{ env.commits }}
      - name: Check out the repository
        run: pwd && ls -la
      - name: ðŸ“ Update CHANGELOG.md
        run: |
          echo "## v${{ github.run_number }} - (${{ env.NOW }})" >> CHANGELOG.md
          echo "commits: $commits" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          cat CHANGELOG.md
