name: Deploy Release to Prod

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (e.g., 1.0.0)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy to prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_PUBLIC_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Logging in to Yandex Container Registry"
            echo "${{ secrets.YANDEX_OAUTH_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex

            # Pull the Docker image
            docker pull cr.yandex/${{ secrets.YANDEX_CONTAINER_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_latest

            # Stop and remove any existing container named 'app' if it exists
            if docker ps -a --format '{{.Names}}' | grep -q '^app$'; then
              docker stop app || true
              docker rm app || true
            fi

            # Run the Docker container with the new image
            docker run -d --restart unless-stopped --name app cr.yandex/${{ secrets.YANDEX_CONTAINER_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_latest

      - name: Create issue content file
        run: |
          echo "**Release v${{ github.event.inputs.release_version }} deployed to production**" > ./deploy_issue_content.md
          echo "**Date**: $(date +%Y-%m-%d)" >> ./deploy_issue_content.md
          echo "**Author**: ${{ github.actor }}" >> ./deploy_issue_content.md

      - name: Add comment to GitHub Issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Release ${{ github.event.inputs.release_version }} Deployed to Prod
          content-filepath: ./deploy_issue_content.md
